// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int NumberOfTimes= Integer.parseInt(args[0]);
		int Greater=0;
		int Lower=0;
		while(NumberOfTimes>0){
			NumberOfTimes--;
			double Random =Math.random();
			if(Random>0.5){
				Greater++;
			} else{
				Lower++;
			}
		}
		System.out.println("> 0.5: " + Greater + " times.");
		System.out.println("<= 0.5: " + Lower + " times.");
	}
}
